# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TRAVIS: 'true' # Skip tests requiring data
      PGHOST: postgres
      PGDATABASE: somutils_test_db
      PGUSER: testdummy
      PGPASSWORD: testdummy_password
    strategy:
      matrix:
        python-version:
          - '2.7'
          - '3.8'
          - '3.9'
    name: Python ${{ matrix.python-version }}
    services:
      postgres: # Required to run dbutils tests
        image: postgres:latest
        env:
          POSTGRES_DB: somutils_test_db
          POSTGRES_USER: testdummy
          POSTGRES_PASSWORD: testdummy_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
#      - name: Install system dependencies
#        run: |
#          sudo apt install gcc libffi-dev libssl-dev nodejs npm libyaml-dev libxslt1-dev
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            coveralls
            pytest-cov
      - name: Install dependencies
        run: |
          pip install -e .
      - name: Unit tests
        run: |
          pytest --cov=somutils somutils
      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel: true
          flag-name: Unit tests

  coveralls_finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
